version: '3'
services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
      args:
        - INSTALL_OPCACHE=true
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  dbdata2:
    driver: local
